name: run-terratest
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: setup
      run: |
        go mod download
        export GOOGLE_PROJECT="${{ secrets.GCP_PROJECT_ID }}"
    - name: run-tests
      run: |
        cd test && go test -v